---
id: slu_theme
description: Package Description
license: commercial
version: 1.0
require:
    kurogo/kurogo-core: '2.0.*'
    kurogo/kurogo-core: '2.1.*'
    kurogo/kurogo-core: '2.2.*'
    kurogo/kurogo-core: '2.3.*'
...
